cabal-version:      3.4
name:               fixen
-- PVP summary:     +-+------- breaking API changes
--                  | | +----- non-breaking API additions
--                  | | | +--- code changes with no API change
--                  | | | | +- dev version
version:            0.0.0.0.1
-- synopsis:
-- description:
license:            MIT
license-file:       LICENSE
author:             Programming Languages Innovation Lab@NUS
maintainer:         yongqi@nus.edu.sg

-- A copyright notice.
-- copyright:
category:           Development
build-type:         Simple
extra-doc-files:    CHANGELOG.md

-- Extra source files to be distributed with the package, such as examples, or a tutorial module.
-- extra-source-files:

common warnings
    ghc-options: -Wall

library 
    -- Import common warning flags.
    import:             warnings
    exposed-modules:    Fixen.BoundVarExplicitor
                      , Fixen.Data.AlaCarte
                      , Fixen.IR.AST
                      , Fixen.IR.Core
                      , Fixen.IR.Core.Annotations
                      , Fixen.IR.ExplicitBoundVars
                      , Fixen.IR.Sorted
                      , Fixen.Monad
                      , Fixen.Pipeline
                      , Fixen.Parser
                      , Fixen.Parser.Common
                      , Fixen.Parser.Expr
                      , Fixen.Parser.Token
                      , Fixen.Parser.Type
                      , Fixen.SymbolSolver
    build-depends:      base ^>=4.19.2.0
                      , filepath ^>=1.4.301.0
                      , diagnose ^>=2.5.1
                      , megaparsec ^>=9.7.0
                      , mtl ^>=2.3.1
                      , transformers ^>=0.6.1.0
                      , containers ^>=0.6.8
                      , parser-combinators ^>=1.3.0
                      , text ^>=2.0
                      , directory
    hs-source-dirs:   src
    default-language: GHC2021


executable fixen
    -- Import common warning flags.
    import:           warnings

    -- .hs or .lhs file containing the Main module.
    main-is:          Main.hs

    -- Modules included in this executable, other than Main.
    other-modules:    CommandLine.Parser
                    , CommandLine.CommandLineArgs
                    , Paths_fixen

    -- LANGUAGE extensions used by modules in this package.
    -- other-extensions:

    -- Other library packages from which modules are imported.
    build-depends:    base ^>=4.19.2.0
                    , optparse-applicative ^>=0.18.1.0
                    , filepath ^>=1.4.301.0
                    , diagnose ^>=2.5.1
                    , megaparsec ^>=9.7.0
                    , mtl ^>=2.3.1
                    , transformers ^>=0.6.1.0
                    , containers ^>=0.6.8
                    , parser-combinators ^>=1.3.0
                    , text ^>=2.0
                    , directory
                    , fixen

    -- Directories containing source files.
    hs-source-dirs:   app

    -- Base language which the package is written in.
    default-language: GHC2021
