name:                fixed-point-lang
version:             0.1.0.0
github:              "githubuser/fixed-point-lang"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2025 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/fixed-point-lang#readme>

dependencies:
- base >= 4.7 && < 5
- megaparsec
- prettyprinter
- text
- containers
- pqueue
- lattices
- haskell-src-exts
- unordered-containers
- hashable
- mtl
- aeson
- bytestring
- deepseq

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

default-extensions:
- OverloadedStrings

library:
  source-dirs: 
  - src
  - Demos

executables:
  fixed-point-lang-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fixed-point-lang

tests:
  fixed-point-lang-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fixed-point-lang
    - tasty
    - tasty-hunit

benchmarks:
  fixed-point-lang-benchmark:
    main: Main.hs
    source-dirs: benchmarks
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - containers
    - directory
    - filepath
    - bytestring
    - text
    - fixed-point-lang
    - criterion
