-- |
--     Module      : Fixen.SymbolSolver.Extern
--     Description : Symbol solving for extern symbols
--     Copyright   : (c) Programming Languages Innovation Lab@NUS
--     License     : MIT
--     Maintainer  : yongqi@nus.edu.sg
--     Stability   : experimental
--
--     This module provides facilities for solving external symbols.
--
--     Symbols are treated as external whenever they are not declared with Fixen.
module Fixen.SymbolSolver.Extern where

import Control.Lens
import Fixen.Fields
import Fixen.IR.AST
import Fixen.Monad
import Fixen.SymbolSolver.Common
import Fixen.SymbolSolver.Validation

-- | Inserts an external symbol into a 'SymbolEnv'. If the symbol already
-- exists in the 'SymbolEnv', it is not inserted.
--
-- @since 0.0.1
initEnvWithExternSymbol
  :: SymbolEnv
  -- ^ The 'SymbolEnv'
  -> SimpleIdentifier
  -- ^ The symbol to insert
  -> FixenPass SymbolState SymbolEnv
initEnvWithExternSymbol env i = do
  let symb_id = simpleIdentifier i
      node_id = i ^. nodeId
  -- check if it already exists; if it does, ignore it.
  case env ^. externInfos . at symb_id of
    Just _ -> return env
    Nothing -> do
      -- validate if this extern symbol is okay to insert
      _ <- validateExternSymbol i env
      return $ env & externInfos . at symb_id ?~ node_id

-- | Performs validation on any extern symbol to be inserted. The rules are:
--
-- * __Against Relations__: External symbols cannot be of the same name as
--   any relation symbol
-- * __Against Queries__: External symbols cannot be of the same name as the
--   name of any query
-- * __Against Fixen-generated Terms__: External symbols cannot be of the same
--   name as any identifier generated by the Fixen compiler
-- * __Against Rule Parameteres__: Warnings will be generated whenever an
--   external symbol is being shadowed by a rule parameter. Warnings are only
--   emitted when the rule parameter being captured is actually used by the
--   rule.
--
-- @since 0.0.1
validateExternSymbol :: SymbolValidator SimpleIdentifier
validateExternSymbol = validate r
  where
    r =
      [ againstRelations
      , againstQueries
      , againstFixenUpperCase
      , againstFixenLowerCase
      , againstRuleParams
      ]
    againstRelations :: SymbolRule SimpleIdentifier
    againstRelations i env =
      validateAgainstRelation
        "an existing use of the same name"
        (simpleIdentifier i)
        i
        env
    againstQueries i env =
      validateAgainstQuery
        "an existing use of the same name"
        (simpleIdentifier i)
        i
        env
    againstFixenUpperCase i env =
      validateAgainstFixenCapitalized
        "external symbol"
        "external symbol"
        (simpleIdentifier i)
        i
        env
    againstFixenLowerCase i env =
      validateAgainstFixenLowercase
        "external symbol"
        "external symbol"
        (simpleIdentifier i)
        i
        env
    againstRuleParams i env =
      warnNameShadowingAgainstBoundVar
        "use of the same name"
        (simpleIdentifier i)
        i
        env
