{-# LANGUAGE OverloadedLists #-}
{-# LANGUAGE OverloadedStrings #-}

-- |
-- Module      : Fixen.SymbolSolver.Prelude
-- Description : Dumping ground for names of stuff that appear in Haskell's Prelude and those generated by Fixen.
-- Copyright   : (c) Programming Languages Innovation Lab@NUS
-- License     : MIT
-- Maintainer  : yongqi@nus.edu.sg
-- Stability   : experimental
--
-- @since 26.7
module Fixen.SymbolSolver.Prelude where

import Data.Set
import Data.Text

--------------------------------------------------------------------------------

-- * Prelude

--------------------------------------------------------------------------------

-- | All uppercase symbols that appear in Haskell's Prelude.
--
-- @since 26.7
preludeTermsCons :: Set Text
preludeTermsCons =
  [ "Applicative"
  , "Bool"
  , "Char"
  , "Double"
  , "Either"
  , "Enum"
  , "EQ"
  , "Eq"
  , "False"
  , "FilePath"
  , "Float"
  , "Floating"
  , "Foldable"
  , "Fractional"
  , "Functor"
  , "GT"
  , "Int"
  , "Integer"
  , "Integral"
  , "IO"
  , "IOError"
  , "IOException"
  , "Just"
  , "Left"
  , "LT"
  , "True"
  , "Maybe"
  , "Monad"
  , "MonadFail"
  , "Monoid"
  , "Nothing"
  , "Num"
  , "Ord"
  , "Ordering"
  , "Ratio"
  , "Rational"
  , "Read"
  , "ReadS"
  , "Real"
  , "RealFrac"
  , "RealFloat"
  , "Right"
  , "Semigroup"
  , "Show"
  , "ShowS"
  , "String"
  , "Traversable"
  , "Word"
  ]

-- | All lowercase symbols that appear in Haskell's Prelude.
--
-- @since 26.7
preludeTerms :: Set Text
preludeTerms =
  [ "abs"
  , "acos"
  , "acosh"
  , "all"
  , "and"
  , "any"
  , "asTypeOf"
  , "asin"
  , "asinh"
  , "atan"
  , "atan2"
  , "atanh"
  , "break"
  , "ceiling"
  , "compare"
  , "concat"
  , "concatMap"
  , "const"
  , "cos"
  , "cosh"
  , "curry"
  , "cycle"
  , "decodeFloat"
  , "div"
  , "divMod"
  , "drop"
  , "dropWhile"
  , "either"
  , "elem"
  , "encodeFloat"
  , "enumFrom"
  , "enumFromThen"
  , "enumFromThenTo"
  , "enumFromTo"
  , "error"
  , "errorWithoutStackTrace"
  , "even"
  , "exp"
  , "exponent"
  , "fail"
  , "filter"
  , "flip"
  , "floatDigits"
  , "floatRadix"
  , "floatRange"
  , "floor"
  , "fmap"
  , "foldMap"
  , "foldl"
  , "foldl'"
  , "foldl1"
  , "foldr"
  , "foldr1"
  , "fromEnum"
  , "fromInteger"
  , "fromIntegral"
  , "fromRational"
  , "fst"
  , "gcd"
  , "getChar"
  , "getContents"
  , "getLine"
  , "head"
  , "id"
  , "init"
  , "interact"
  , "ioError"
  , "isDenormalized"
  , "isIEEE"
  , "isInfinite"
  , "isNaN"
  , "isNegativeZero"
  , "iterate"
  , "last"
  , "lcm"
  , "length"
  , "lex"
  , "lines"
  , "log"
  , "logBase"
  , "lookup"
  , "map"
  , "mapM"
  , "mapM_"
  , "mappend"
  , "max"
  , "maxBound"
  , "maximum"
  , "maybe"
  , "mconcat"
  , "mempty"
  , "min"
  , "minBound"
  , "minimum"
  , "mod"
  , "negate"
  , "not"
  , "notElem"
  , "null"
  , "odd"
  , "or"
  , "otherwise"
  , "pi"
  , "pred"
  , "print"
  , "product"
  , "properFraction"
  , "pure"
  , "putChar"
  , "putStr"
  , "putStrLn"
  , "quot"
  , "quotRem"
  , "read"
  , "readFile"
  , "readIO"
  , "readList"
  , "readLn"
  , "readParen"
  , "reads"
  , "readsPrec"
  , "realToFrac"
  , "recip"
  , "rem"
  , "repeat"
  , "replicate"
  , "return"
  , "round"
  , "scaleFloat"
  , "scanl"
  , "scanl1"
  , "scanr1"
  , "seq"
  , "sequence"
  , "sequenceA"
  , "sequence_"
  , "show"
  , "showChar"
  , "showList"
  , "showParen"
  , "showString"
  , "shows"
  , "showsPrec"
  , "significand"
  , "signum"
  , "sin"
  , "sinh"
  , "snd"
  , "span"
  , "splitAt"
  , "sqrt"
  , "subtract"
  , "succ"
  , "sum"
  , "tail"
  , "take"
  , "takeWhile"
  , "tan"
  , "tanh"
  , "toEnum"
  , "toInteger"
  , "toRational"
  , "traverse"
  , "truncate"
  , "uncurry"
  , "undefined"
  , "unlines"
  , "until"
  , "unwords"
  , "unzip"
  , "unzip3"
  , "userError"
  , "words"
  , "writeFile"
  , "zip"
  , "zip3"
  , "zipWith"
  , "zipWith3"
  ]

--------------------------------------------------------------------------------

-- * Fixen

--------------------------------------------------------------------------------

-- | Lowercase stuff generated by Fixen.
--
-- @since 26.7
fixenTerms :: Set Text
fixenTerms =
  fromList
    [ "step"
    , "solve"
    , "reSolve"
    , "evaluate"
    ]

-- | Uppercase stuff generated by Fixen.
--
-- @since 26.7
fixenTypesCons :: Set Text
fixenTypesCons =
  fromList
    [ "Database"
    , "RuleInstance"
    , "Fact"
    , "Interpretation"
    , "Phases"
    ]
