-- |
-- Module      : Fixen.SymbolSolver.Query
-- Description : Symbol solving for queries
-- Copyright   : (c) Programming Languages Innovation Lab@NUS
-- License     : MIT
-- Maintainer  : yongqi@nus.edu.sg
-- Stability   : experimental
--
-- This module provides facilities for solving query declarations.
--
-- @since 0.0.1
module Fixen.SymbolSolver.Query where

import Control.Lens
import Fixen.Fields
import Fixen.IR.AST
import Fixen.Monad
import Fixen.SymbolSolver.Common
import Fixen.SymbolSolver.Validation

--------------------------------------------------------------------------------

-- * Main Entry Point

-- $mainEntryPoint
--
-- You should only need 'initEnvWithQuery'.

--------------------------------------------------------------------------------

-- | Initializes a 'SymbolEnv' with a 'Query' declaration.
--
-- /Precondition/: 'RelationDeclaration's must have been initialized in the 'SymbolEnv'
--
-- @since 0.0.1
initEnvWithQuery
  :: SymbolState σ
  => SymbolEnv
  -- ^ The 'SymbolEnv'
  -> Query
  -- ^ The 'Query'
  -> FixenPass σ SymbolEnv
initEnvWithQuery env q = do
  _ <- validateQuery q env
  let q_repr = simpleIdentifier $ q ^. name
  -- perform the insertion if it doesn't already exist
  case env ^. queryInfos . at q_repr of
    Just _ -> return env
    Nothing -> return $ env & queryInfos . at q_repr ?~ q

--------------------------------------------------------------------------------

-- * Helpers

--------------------------------------------------------------------------------

-- | Validates a 'Query' declaration. The rules are:
--
-- * __Against Other Queries__: The query being declared must not have the same
--   name as other queries.
-- * __Against Extern Symbols__: The query being declared must not have the
--   same name as an external symbol. Note that a symbol is considered
--   \"external\" if it is not declared within the Fixen program.
-- * __Against Relations__: The relation being queried must exist and have the
--   right arity.
-- * __Against Fixen-generated Terms__: The query being declared must not have
--   the same name as any term generated by Fixen.
-- * __Against Prelude Terms__: A warning is emitted whenever the query being
--   declared has the same name as a term in Prelude.
--
-- @since 0.0.1
validateQuery :: SymbolState σ => SymbolValidator σ Query
validateQuery = validate r
  where
    r =
      [ againstOtherQueries
      , againstExtern
      , matchRelationArity
      , againstPrelude
      , againstFixen
      ]

    againstOtherQueries =
      validateNamed
        ( validateAgainstQuery
            "another query declaration with the same name"
        )

    againstExtern =
      validateNamed
        (validateAgainstExtern "query declaration" queryValidationErrorNotes)

    againstPrelude =
      validateNamed
        (warnAgainstPreludeLowercase "query declaration" "query declaration")

    againstFixen =
      validateNamed
        (validateAgainstFixenLowercase "query declaration" "query declaration")

    matchRelationArity q env =
      let rel = queryRel q
       in relationExistsAndHasRightArity rel "query" env
