{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultilineStrings #-}

-- |
-- Module      : Fixen.CodeGen.Import
-- Description : Code Generation for Haskell import statements
-- Copyright   : (c) Programming Languages Innovation Lab@NUS
-- License     : MIT
-- Maintainer  : yongqi@nus.edu.sg
-- Stability   : experimental
--
-- This module provides code-generation facilities for 'HsImport's.
--
-- User-declared import statements ('HsImport'), along with pre-baked 
-- module imports needed by the generated Fixen module, are generated by this
-- code generator.
--
-- @since 26.7
module Fixen.CodeGen.Import where

import Data.Text (Text)
import Data.Text qualified as Text
import Fixen.Fields
import Fixen.IR.AST

--------------------------------------------------------------------------------

-- * Main Entry Point

--------------------------------------------------------------------------------

-- | Generates the import statements for the generated Haskell module.
--
-- @since 26.7
codeGenImports :: Program -> Text
codeGenImports prog = 
  let user_imports =
        if null (prog ^. imports) 
          then "" 
          else 
            prog ^. imports 
              <&> codeGenImportStmt
              & Text.intercalate "\n"
              & Text.append "\n\n----- USER IMPORTS -----\n"
   in Text.append fixenImports user_imports

--------------------------------------------------------------------------------

-- * Helpers

--------------------------------------------------------------------------------

-- | Generates the Haskell import statement from a 'HsImport'.
--
-- @since 26.7
codeGenImportStmt :: HsImport -> Text
codeGenImportStmt i =
  let n = i ^. moduleName
   in Text.concat [ "import "
                  , if hsImportQualified i then "qualified " else ""
                  , fullIdentifier n
                  , maybe "" (\a -> Text.concat [" as ", fullIdentifier a]) (hsImportAlias i)
                  , maybe "" (Text.cons ' ') (hsImportSpecs i)
                  ]

-- | The import statements that are always produced by the Fixen compiler.
--
-- @since 26.7
fixenImports :: Text
fixenImports = 
  """
  ----- FIXEN IMPORTS -----
  import Data.HashMap.Strict (HashMap)
  import qualified Data.HashMap.Strict as HashMap
  import Data.HashSet (HashSet)
  import qualified Data.HashSet as HashSet
  import Data.Maybe
  import Control.Monad
  import qualified Data.PQueue.Max as Q
  """
