-- {-# LANGUAGE DataKinds #-}
{-# LANGUAGE OverloadedStrings #-}

-- {-# LANGUAGE PatternSynonyms #-}
-- {-# LANGUAGE ViewPatterns #-}
-- {-# LANGUAGE TypeAbstractions #-}

module Fixen.SymbolSolver where

-- import Data.Text

import Control.Monad (foldM, forM_, when)
import Data.Function ((&))
import Data.Functor ((<&>))
import Data.IntSet qualified as IntSet
import Data.List (nubBy)
import Data.List.NonEmpty
import Data.Map.Strict qualified as Map
import Data.Set qualified as Set
import Data.Text
import Fixen.Data.NodeId
import Fixen.IR.AST
import Fixen.Monad
import Fixen.SymbolSolver.Common
import Fixen.SymbolSolver.PartialOrdDeclaration
import Fixen.SymbolSolver.Prelude
import Fixen.SymbolSolver.Query
import Fixen.SymbolSolver.Relation

solveSymbols :: Program -> FixenPass SymbolState SymbolEnv
solveSymbols prog = do
  env_with_rels_and_pords <-
    pure emptySymbolEnv
      -- gather partial ord declarations
      >>= foldMWith initEnvWithPartialOrd (partialOrdDeclarations prog)
      -- gather relations
      >>= foldMWith initEnvWithRelation (relations prog)
  -- flush all errors, and continue. Now, we are certain that the relations and partialOrdDeclarations
  -- are correctly added to the symbol environment.
  failIfErrored
  env_with_queries <- foldM initEnvWithQuery env_with_rels_and_pords (queries prog)
  return env_with_queries

-- initEnvWithRule :: SymbolEnv -> Rule -> FixenPass SymbolState SymbolEnv
-- initEnvWithRule env r = do
--   -- get the bound variables.
--   rule_bound_vars <- getRuleBoundVars env r
--   warnUnusedBoundVars r rule_bound_vars
--   undefined
--
-- -- | Obtains the bound variables of the rule. If they were not defined
-- -- by the user, they will be inferred from assumptions of the rule. Duplicate
-- -- bound variables will cause errors. Variables whose name shadows external
-- -- symbols (including prelude terms) will throw warnings
-- getRuleBoundVars :: SymbolEnv -> Rule -> FixenPass SymbolState [SimpleIdentifier]
-- getRuleBoundVars env r = do
--   -- get the bound variables.
--   let rule_bound_vars =
--         case Fixen.IR.AST.ruleBoundVars r of
--           [] -> getAssumptionVariables r
--           v -> v
--       -- time to look for duplicate bound variables (that happens when users
--       -- specify bound variables and misspelled them probably)
--       freq_map =
--         rule_bound_vars
--           <&> (\i -> Map.singleton (simpleIdentifier i) (Set.singleton i))
--           & Map.unionsWith Set.union
--       -- filter the values
--       dup_vars =
--         freq_map
--           & Map.filter (\x -> Set.size x > 1)
--           & Map.toList
--           <&> snd
--   -- Get the unique bound variables after throwing errors
--   nub_bv <-
--     if not (Prelude.null dup_vars)
--       then do
--         -- handle the errors
--         forM_ dup_vars handleDupErrors
--         return $ Data.List.nubBy (===) rule_bound_vars
--       else return rule_bound_vars
--   forM_ nub_bv (warnBoundVarExtern env)
--   return nub_bv
--
-- getAssumptionVariables :: Rule -> [SimpleIdentifier]
-- getAssumptionVariables r =
--   -- get the assumptions
--   Fixen.IR.AST.ruleAssumptions r
--     -- get the relation parameters
--     <&> relationParams
--     -- concatenate them to get one giant list of simple identifiers
--     & Prelude.concat
--     -- get the unique ones
--     & Data.List.nubBy (===)
--
-- warnUnusedBoundVars :: Rule -> [SimpleIdentifier] -> FixenPass SymbolState ()
-- warnUnusedBoundVars rule bvs = do
--   let used = getAssumptionVariables rule
--       unused = Prelude.filter (not . (`Prelude.elem` used)) bvs
--   forM_ unused warnUnusedBoundVar
--
-- warnUnusedBoundVar :: SimpleIdentifier -> FixenPass SymbolState ()
-- warnUnusedBoundVar i = do
--   pos <- fixenGetPosition i
--   accumWarn
--     Nothing
--     "unused variable"
--     [(pos, This "variable")]
--     []
--
-- warnBoundVarExtern :: SymbolEnv -> SimpleIdentifier -> FixenPass SymbolState ()
-- warnBoundVarExtern env i =
--   case (externInfo $ info env) Map.!? simpleIdentifier i of
--     Just t -> do
--       pos <- fixenGetPosition i
--       pos' <- fixenGetPosition t
--       accumWarn
--         Nothing
--         "name shadowing"
--         [(pos, This "variable"), (pos', Where "external symbol")]
--         [Hint "change the name of this variable"]
--     Nothing -> do
--       if simpleIdentifier i `Set.member` preludeTerms
--         then do
--           pos <- fixenGetPosition i
--           accumWarn
--             Nothing
--             "potential name clash with Prelude terms"
--             [(pos, This "variable")]
--             [Hint "hide this name from the Prelude import, or change the name of this variable"]
--         else return ()
--
-- handleDupErrors :: Set.Set SimpleIdentifier -> FixenPass SymbolState ()
-- handleDupErrors s = do
--   poss <- mapM fixenGetPosition (Set.toList s)
--   let errs = (\pos -> (pos, This "variable")) <$> poss
--   accumErr
--     Nothing
--     "duplicate variable names"
--     errs
--     [Note "queries cannot share names with \"external\" terms used in the program (these include other queries)"]

-- The symbol solver must perform two things:
-- 1. Make sure every var is either locally bound or extern, not neither.
-- 2. Make sure there are no name clashes:
--    1. relations vs relations
--    2. relations vs Types
--    3. rules vs rules
--    4. rules vs externs
--    5. bound vars variables vs rules
--    6. bound vars vs externs
-- 3. Warn on unused variables.
--
-- Procedure:
-- Create a symbol environment. These contain:
-- highest priority symbols (the symbols that most likely specifies the
-- programmers true intent)
-- - rule names and a reference to the rule.
-- - relation names and an arity with types and reference to the relation
-- - externs declarations
--
-- walk down:
--  relations, gathering

-- import Control.Monad
-- import Data.Map.Strict as Map
-- import Data.Set as Set
-- import Data.Text
-- import Error.Diagnose.Position
-- import Error.Diagnose.Report
-- import Fixen.Data.AlaCarte
-- import Fixen.IR.AST qualified as AST
-- import Fixen.IR.Core
-- import Fixen.IR.ExplicitBoundVars qualified as E
-- import Fixen.Monad
-- import Control.Monad.IO.Class (MonadIO(liftIO))
--
-- type NameType = CoreItem "SymbolSolver.NameType" () Text
-- type ApplicationType = CoreDouble "SymbolSolver.AppType" ()
-- type ActualType = Fixpoint (NameType ::+:: ApplicationType)
--
-- pattern NameType :: Text -> ActualType
-- pattern NameType t <- ((↓↓?) -> Just (CoreItem @"SymbolSolver.NameType" () t))
--   where
--     NameType t = (↑↑) (CoreItem @"SymbolSolver.NameType" () t)
--
-- pattern ApplicationType :: ActualType -> ActualType -> ActualType
-- pattern ApplicationType t t' <- ((↓↓?) -> Just (CoreDouble @"SymbolSolver.AppType" () t t'))
--   where
--     ApplicationType t t' = (↑↑) (CoreDouble @"SymbolSolver.AppType" () t t')
--
-- data TypeLattice
--   = Dynamic
--   | ActualType ActualType
--   | Top
--   deriving (Show, Eq)
--
-- data BoundVarInfo
--   = BoundVarInfo {boundVarUsage :: [(Int, Int)], boundVarType :: TypeLattice}
--   | UnknownBoundVarInfo
--   deriving (Show, Eq)
--
-- data RelationInfo
--   = RelationInfo
--       { relArgs :: [(ActualType, Position)]
--       , relPos :: Position
--       }
--   | UnknownRelationInfo
--   deriving (Show, Eq)
--
-- data RuleInfo = RuleInfo
--   { ruleBoundVars :: Map.Map Text ActualType
--   }
--   deriving (Show, Eq)
--
-- data SymbolEnv = SymbolEnv
--   { relations :: Map.Map Text RelationInfo
--   , rules :: Map.Map Int RuleInfo
--   , externs :: Map.Map Text Position
--   }
--   deriving (Show, Eq)
--
-- data Reason = Reason Position Position
--   deriving (Show, Eq)
--

-- solveSymbols :: E.Program -> FixenPass FixenErrors SymbolEnv
-- solveSymbols pgm = do
--   let env = SymbolEnv Map.empty Map.empty Map.empty
--   -- do a name check on the explicitly declared stuff by the user.
--   rel_name_env <- foldM foldRelNames Map.empty $ E.relations pgm
--   rul_name_env <- foldM foldRuleNames Map.empty $ E.rules pgm
--   extern_name_env <- case E.externs pgm of
--     Just (AST.Extern _ ls) -> foldM (foldExterns rul_name_env) Map.empty ls
--     Nothing -> return Map.empty
--   let completions = (\(AST.Relation _ _ _ comp) -> comp) <$> E.relations pgm
--   extern_env <- foldM (foldCompletions rul_name_env) extern_name_env completions
--   failIfErrored
--   -- walk rels
--   rel_env <- foldM (walkRelations rel_name_env) Map.empty $ E.relations pgm
--   -- walk rules
--   rul_env <- walkRules rel_env extern_env rul_name_env Map.empty $ E.rules pgm
--   return env {relations = rel_env, externs = extern_env, rules = rul_env}
--
-- walkRules :: Map.Map Text RelationInfo -> Map.Map Text Position -> Map.Map Text E.Rule -> Map.Map Int RuleInfo -> [E.Rule] -> FixenPass FixenErrors (Map.Map Int RuleInfo)
-- walkRules rel_env extern_env rule_name_env mp_ ls = go mp_ 0 ls
--   where
--     go :: Map.Map Int RuleInfo -> Int -> [E.Rule] -> FixenPass FixenErrors (Map.Map Int RuleInfo)
--     go mp _ [] = return mp
--     go mp n (rule : rules) = do
--       rule' <- walkRule rule
--       go (Map.insert n rule' mp) (n + 1) rules
--     walkRule :: E.Rule -> FixenPass FixenErrors RuleInfo
--     walkRule (E.Rule _ _ (E.RuleBoundVars _ rule_bound_vars) premises conclusion) = do
--       are_bound_vars_unique Map.empty rule_bound_vars
--       are_bvs_rule_names premises rule_bound_vars
--       are_bvs_externs premises rule_bound_vars
--       are_bvs_unused premises conclusion rule_bound_vars
--       -- at this point the bvs are okay. What is left is to make sure that
--       -- the premises and conclusions are well-formed, and we can do type checking in the meantime
--       let bv_env = Set.fromList $ (\(E.BoundVar _ t) -> t) <$> rule_bound_vars
--       t1 <- arePremisesWellFormed bv_env premises
--       t2 <- isConclusionWellFormed bv_env t1 conclusion
--       failIfErrored
--       t3 <-
--         mapM
--           ( \(l, _) -> case l of
--               ActualType x -> return x
--               _ -> error $ "MOZZARELLAERROR: THIS SHOULD NEVER HAPPEN? AFTER UNIFICATION TYPE IS " ++ show l
--           )
--           t2
--       return $ RuleInfo t3
--     isConclusionWellFormed :: Set.Set Text -> Map.Map Text (TypeLattice, Reason) -> AST.Conclusion -> FixenPass FixenErrors (Map.Map Text (TypeLattice, Reason))
--     isConclusionWellFormed bv_env ty_map (AST.Conclusion concl_pos (AST.TypeLetterIdentifier _ concl_name) (AST.ConclusionArguments _ args)) = do
--       -- make sure name of conclusion is a relation
--       -- TODO: If it's the name of a type, it would be good to say so.
--       case Map.lookup concl_name rel_env of
--         Nothing -> failR $ Err Nothing "relation not found" [(concl_pos, This $ unpack concl_name ++ " is not a declared relation")] []
--         Just rel_info -> do
--           let rel_args = relArgs rel_info
--               rel_pos = relPos rel_info
--           when (Prelude.length args /= Prelude.length rel_args) $
--             failR $
--               Err Nothing "relation arguments do not match relation parameters" [(concl_pos, This $ unpack concl_name ++ " applied to " ++ show (Prelude.length args) ++ " arguments"), (rel_pos, Where $ unpack concl_name ++ " declared with " ++ show (Prelude.length rel_args) ++ " parameters")] []
--           foldM
--             ( \tmap (e, (ty, ty_pos)) ->
--                 case e of
--                   AST.ExprTermVar _ (AST.TermIdentifierAlpha (AST.TermLetterIdentifier id_pos v)) -> do
--                     -- check that it is a valid variable in the first place
--                     unless (Set.member v bv_env || Set.member v preludeTerms || Map.member v extern_env) $ do
--                       accumR $ Err Nothing "unknown variable" [(id_pos, This "not declared as rule bound variable or extern")] []
--
--                     case Map.lookup v tmap of
--                       Nothing ->
--                         -- no idea what the type of v is -- is extern;
--                         return tmap
--                       Just (Top, _) -> return tmap -- already failed somewhere
--                       Just (Dynamic, _) -> return tmap -- already extern
--                       Just (ActualType ty', Reason id_pos' ty_pos') -> if ty /= ty' then accumR (Err Nothing "type mismatch" [(id_pos', Where $ unpack v ++ " used here"), (ty_pos', Where $ unpack v ++ " must have this type"), (id_pos, This $ unpack v ++ " also used here"), (ty_pos, Where "must also have this type")] []) >> return (Map.insert v (Top, Reason id_pos ty_pos) tmap) else return tmap
--                   e' -> walkExpr bv_env extern_env e' >> return tmap -- dont bother type checking anymore. just walk the expression.
--             )
--             ty_map
--             (Prelude.zip args rel_args)
--
--     arePremisesWellFormed :: Set.Set Text -> AST.RulePremises -> FixenPass FixenErrors (Map.Map Text (TypeLattice, Reason))
--     arePremisesWellFormed bv_env (AST.RulePremises _ ls') = foldM (isPremiseWellFormed bv_env) Map.empty ls'
--     isPremiseWellFormed :: Set.Set Text -> Map.Map Text (TypeLattice, Reason) -> AST.Premise -> FixenPass FixenErrors (Map.Map Text (TypeLattice, Reason))
--     isPremiseWellFormed bv_env mp (AST.PremiseAssumption pos (AST.TypeLetterIdentifier _ t) (AST.AssumptionArguments _ args)) = do
--       case Map.lookup t rel_env of
--         Nothing -> do failR $ Err Nothing "relation not found" [(pos, This $ unpack t ++ " is not a declared relation")] []
--         Just rel_info -> do
--           -- relation exists. get the number of args
--           let rel_args = relArgs rel_info
--               rel_pos = relPos rel_info
--           when (Prelude.length args /= Prelude.length rel_args) $
--             failR $
--               Err Nothing "relation arguments do not match relation parameters" [(pos, This $ unpack t ++ " applied to " ++ show (Prelude.length args) ++ " arguments"), (rel_pos, Where $ unpack t ++ " declared with " ++ show (Prelude.length rel_args) ++ " parameters")] []
--           -- check each variable to see if they are in the bound vars.
--           forM_
--             args
--             ( \(CoreItem pos' v) ->
--                 unless (Set.member v bv_env) $
--                   failR $
--                     Err Nothing "variable not found" [(pos', This $ unpack v ++ " is not a bound variable in this rule")] []
--             )
--           -- now same number of args as params. also, args are actually bound.
--           -- type check!
--           foldM
--             ( \tymap (AST.TermLetterIdentifier id_pos i, (ty, ty_pos)) ->
--                 case Map.lookup i tymap of
--                   Nothing -> return $ Map.insert i (ActualType ty, Reason id_pos ty_pos) tymap
--                   Just (Top, _) -> return tymap
--                   Just (Dynamic, _) -> return $ Map.insert i (ActualType ty, Reason id_pos ty_pos) tymap
--                   Just (ActualType ty', Reason id_pos' ty_pos') -> if ty /= ty' then accumR (Err Nothing "type mismatch" [(id_pos', Where $ unpack i ++ " used here"), (ty_pos', Where $ unpack i ++ " must have this type"), (id_pos, This $ unpack i ++ " also used here"), (ty_pos, Where $ unpack i ++ " must also have this type")] []) >> return (Map.insert i (Top, Reason id_pos ty_pos) tymap) else return tymap
--             )
--             mp
--             (Prelude.zip args rel_args)
--     isPremiseWellFormed bv_env mp (AST.PremiseCondition _ expr) = do
--       -- dont bother type checking here. just check if the vars are declared somewhere.
--       -- reason why we don't type check even if given something like `if v` where v is a bound var is because maybe the type of v is actually Bool.
--       walkExpr bv_env extern_env expr
--       return mp
--
--     are_bound_vars_unique :: Map.Map Text E.BoundVar -> [E.BoundVar] -> FixenPass FixenErrors ()
--     are_bound_vars_unique _ [] = return ()
--     are_bound_vars_unique s (bv@(E.BoundVar bv_pos v) : bvs) = do
--       case Map.lookup v s of
--         Just (E.BoundVar bv_pos' v') ->
--           case (bv_pos, bv_pos') of
--             (E.SourcePosition pos, E.SourcePosition pos') -> do
--               failR $ Err Nothing "duplicate bound variables" [(pos', This $ "bound variable called " ++ unpack v'), (pos, This $ "bound variable also called " ++ unpack v)] [Note "cannot have duplicate bound variables"]
--             _ -> error "MOZZARELLA EXCEPTION: CANNOT BE THE CASE. TODO: CLEAN THIS UP!"
--         Nothing ->
--           are_bound_vars_unique (Map.insert v bv s) bvs
--     are_bvs_rule_names :: AST.RulePremises -> [E.BoundVar] -> FixenPass FixenErrors ()
--     are_bvs_rule_names _ [] = return ()
--     are_bvs_rule_names premises (E.BoundVar bv_pos v : bvs) = do
--       case Map.lookup v rule_name_env of
--         Just (E.Rule rule_pos _ _ _ _) -> do
--           let notes = case bv_pos of
--                 E.SourcePosition pos -> [(rule_pos, Where $ "rule is named " ++ unpack v), (pos, This $ "variable is also named " ++ unpack v)]
--                 E.Inferred args ->
--                   let ls' = f premises <$> args
--                   in  (rule_pos, Where $ "rule is named " ++ unpack v) : ls'
--
--           failR $ Err Nothing "variable has same name as rule" notes []
--         Nothing -> are_bvs_rule_names premises bvs
--     are_bvs_externs :: AST.RulePremises -> [E.BoundVar] -> FixenPass FixenErrors ()
--     are_bvs_externs _ [] = return ()
--     are_bvs_externs premises (E.BoundVar bv_pos v : bvs) = do
--       case Map.lookup v extern_env of
--         Just pos ->
--           let notes = case bv_pos of
--                 E.SourcePosition pos' -> [(pos, Where $ "external symbol " ++ unpack v ++ " is imported"), (pos', This $ "variable is also named " ++ unpack v)]
--                 E.Inferred args ->
--                   let ls' = f premises <$> args
--                   in  (pos, Where $ "external symbol " ++ unpack v ++ " is imported") : ls'
--           in  failR $ Err Nothing "variable has same name as external symbols" notes []
--         Nothing -> are_bvs_externs premises bvs
--     are_bvs_unused :: AST.RulePremises -> AST.Conclusion -> [E.BoundVar] -> FixenPass FixenErrors ()
--     are_bvs_unused premises concl bvs = do
--       let used = Set.union (getAllVarsFromPremises premises) (getAllVarsFromConclusion concl)
--       -- liftIO $ print used
--       let unused = Prelude.filter (\(E.BoundVar _ v) -> v `Set.notMember` used) bvs
--       let warns =
--             ( \(E.BoundVar pos _) -> case pos of
--                 E.SourcePosition p -> (p, This "unused")
--                 E.Inferred _ -> error "NO WAY THIS CAN POSSIBLY HAPPEN!"
--             )
--               <$> unused
--       unless (Prelude.null warns) $
--         accumR $
--           Warn Nothing "unused variables" warns []
--
-- -- TODO: if its in the rule env it would be good to say so.
-- walkExpr :: Set.Set Text -> Map.Map Text Position -> AST.Expr -> FixenPass FixenErrors ()
-- walkExpr bv_env extern_env (AST.ExprTermVar pos (AST.TermIdentifierAlpha (AST.TermLetterIdentifier _ v))) = do
--   unless (Set.member v bv_env || Set.member v preludeTerms || Map.member v extern_env) $ do
--     accumR $ Err Nothing "unknown variable" [(pos, This "not declared as rule bound variable or extern")] []
-- walkExpr bv_env extern_env (AST.ExprApp app_pos (AST.ExprTermVar pos (AST.TermIdentifierAlpha (AST.TermLetterIdentifier _ v))) e') = do
--   when (Set.member v bv_env) $
--     accumR $
--       Err Nothing "type mismatch" [(app_pos, This "rule variable cannot be applied to arguments")] []
--   unless (Set.member v bv_env || Set.member v preludeTerms || Map.member v extern_env) $ do
--     accumR $ Err Nothing "unknown variable" [(pos, This "not declared as rule bound variable or extern")] []
--   walkExpr bv_env extern_env e'
-- walkExpr bv_env extern_env (AST.ExprApp _ e e') = walkExpr bv_env extern_env e >> walkExpr bv_env extern_env e'
-- walkExpr _ _ _ = return ()
--
-- getAllVarsFromPremises :: AST.RulePremises -> Set.Set Text
-- getAllVarsFromPremises (AST.RulePremises _ ls) = Set.unions $ getAllVarsFromPremise <$> ls
--
-- getAllVarsFromPremise :: AST.Premise -> Set.Set Text
-- getAllVarsFromPremise (AST.PremiseAssumption _ _ (AST.AssumptionArguments _ ls)) = Set.fromList $ (\(CoreItem _ t) -> t) <$> ls
-- getAllVarsFromPremise (AST.PremiseCondition _ e) = getAllVarsFromExpr e
--
-- getAllVarsFromExpr :: AST.Expr -> Set.Set Text
-- getAllVarsFromExpr (AST.ExprTermVar _ (AST.TermIdentifierAlpha (CoreItem _ v))) = Set.singleton v
-- getAllVarsFromExpr (AST.ExprApp _ e e') = Set.union (getAllVarsFromExpr e) (getAllVarsFromExpr e')
-- getAllVarsFromExpr _ = Set.empty
--
-- getAllVarsFromConclusion :: AST.Conclusion -> Set.Set Text
-- getAllVarsFromConclusion (AST.Conclusion _ _ (AST.ConclusionArguments _ ls)) = Set.unions $ getAllVarsFromExpr <$> ls
--
-- f :: AST.RulePremises -> (Int, Int) -> (Position, Marker String)
-- f (AST.RulePremises _ ls) (x, y) =
--   let ass = ls !! x
--   in  case ass of
--         AST.PremiseAssumption _ _ (AST.AssumptionArguments _ args) ->
--           let (CoreItem pos v) = args !! y
--           in  (pos, This $ "occurrences of " ++ unpack v)
--         _ -> error "MOZZARELLA EXCEPTION: CANNOT BE THE CASE. WHEN WE ANNOTATE BOUND VARIABLES WITH OCCURRENCES (I.E. FORMING OUR OWN BOUND VAR LIST), THEY MUST COME FROM ASSUMPTIONS, NOT CONDITIONS!!!!!"
--
-- walkRelations :: Map.Map Text AST.Relation -> Map.Map Text RelationInfo -> AST.Relation -> FixenPass FixenErrors (Map.Map Text RelationInfo)
-- walkRelations rel_name_env mp (AST.Relation pos (AST.TypeLetterIdentifier _ n) (AST.RelationSignature _ ls) _) = do
--   -- make sure that types don't share names with relations!
--   forM_ ls walkTypes
--   let t = createRawType <$> ls
--   return $ Map.insert n (RelationInfo t pos) mp
--   where
--     walkTypes :: AST.Type -> FixenPass FixenErrors ()
--     walkTypes (AST.TypeVar posT (AST.TypeIdentifier _ nT)) =
--       case Map.lookup nT rel_name_env of
--         Just (AST.Relation rel_pos _ _ _) ->
--           failR $ Err Nothing "relation cannot be used as type" [(rel_pos, Where "this relation"), (posT, This "this type shares the same name")] []
--         Nothing -> return ()
--     walkTypes (AST.TypeApp _ t t') = walkTypes t >> walkTypes t'
--
-- createRawType :: AST.Type -> (ActualType, Position)
-- createRawType (AST.TypeVar pos (AST.TypeIdentifier _ n)) = (NameType n, pos)
-- createRawType (AST.TypeApp pos t t') = (ApplicationType (createRawType' t) (createRawType' t'), pos)
--
-- createRawType' :: AST.Type -> ActualType
-- createRawType' (AST.TypeVar _ (AST.TypeIdentifier _ n)) = NameType n
-- createRawType' (AST.TypeApp _ t t') = ApplicationType (createRawType' t) (createRawType' t')
--
-- foldCompletions :: Map.Map Text E.Rule -> Map.Map Text Position -> Maybe AST.Completion -> FixenPass FixenErrors (Map.Map Text Position)
-- foldCompletions _ mp2 Nothing = return mp2
-- foldCompletions mp mp2 (Just (AST.Completion pos (AST.TermLetterIdentifier _ n))) = do
--   case Map.lookup n mp of
--     Just (CoreRule pos1 _ _ _ _) -> do
--       accumR $
--         Err
--           Nothing
--           "rule and completion names clash"
--           [ (pos1, Where $ "A rule named " ++ unpack n ++ " is declared here")
--           , (pos, This $ "A completion named " ++ unpack n ++ " is imported here")
--           , (pos1, Maybe "change the name of this rule")
--           ]
--           [Note "rules in the program cannot have the same name as a completion (it is externally declared)"]
--       return mp2
--     Nothing -> case Map.lookup n mp2 of
--       Nothing -> return $ Map.insert n pos mp2
--       Just _ -> return mp2
--
-- foldExterns :: Map.Map Text E.Rule -> Map.Map Text Position -> AST.TermLetterIdentifier -> FixenPass FixenErrors (Map.Map Text Position)
-- foldExterns mp mp2 (AST.TermLetterIdentifier p n) = do
--   case Map.lookup n mp of
--     Just (CoreRule pos1 _ _ _ _) -> do
--       accumR $
--         Err
--           Nothing
--           "rule and extern names clash"
--           [ (pos1, Where $ "A rule named " ++ unpack n ++ " is declared here")
--           , (p, This $ "An external declaration named " ++ unpack n ++ " is imported here")
--           , (pos1, Maybe "change the name of this rule")
--           ]
--           [Note "rules in the program cannot have the same name as an external declaration"]
--       return mp2
--     Nothing -> case Map.lookup n mp2 of
--       Just p2 -> do
--         accumR $
--           Warn Nothing "duplicate extern declarations" [(p2, Where "imported here"), (p, This "also imported here")] [Hint "extern declarations need only be imported once"]
--         return mp2
--       Nothing -> return $ Map.insert n p mp2
--
-- foldRelNames
--   :: Map.Map Text AST.Relation
--   -> AST.Relation
--   -> FixenPass FixenErrors (Map.Map Text AST.Relation)
-- foldRelNames mp rel@(CoreRelation pos2 (CoreItem p n2) _ _) = do
--   when
--     (Set.member n2 preludeTermsCons)
--     ( accumR $
--         Err
--           Nothing
--           "relation name clashes with Haskell Prelude name"
--           [(pos2, This "relation name already defined in Haskell's Prelude")]
--           [Note "use unique names to avoid name clashes"]
--     )
--   case Map.lookup n2 mp of
--     Just (CoreRelation pos1 _ _ _) -> do
--       accumR $
--         Err
--           Nothing
--           "duplicate relation names"
--           [ (pos1, Where $ "A relation named " ++ unpack n2 ++ " already declared here")
--           , (pos2, This $ "A relation named " ++ unpack n2 ++ " declared here")
--           , (p, Maybe "change the name of this relation")
--           ]
--           [Note "relations in the program must have unique names"]
--       return mp
--     Nothing -> return $ Map.insert n2 rel mp
--
-- foldRuleNames :: Map.Map Text E.Rule -> E.Rule -> FixenPass FixenErrors (Map.Map Text E.Rule)
-- foldRuleNames mp rul@(CoreRule pos (Just (AST.TermLetterIdentifier p n)) _ _ _) = do
--   when
--     (Set.member n preludeTerms)
--     ( accumR $
--         Err
--           Nothing
--           "rule name clashes with Haskell Prelude name"
--           [(pos, This "rule name already defined in Haskell's Prelude")]
--           [Note "use unique names to avoid name clashes"]
--     )
--   case Map.lookup n mp of
--     Just (CoreRule pos1 _ _ _ _) -> do
--       accumR $
--         Err
--           Nothing
--           "duplicate rule names"
--           [ (pos1, Where $ "A rule named " ++ unpack n ++ " already declared here")
--           , (pos, This $ "A rule named " ++ unpack n ++ " declared here")
--           , (p, Maybe "change the name of this rule")
--           ]
--           [Note "rule in the program must have unique names"]
--       return mp
--     Nothing -> return $ Map.insert n rul mp
-- foldRuleNames mp _ = return mp
