-- |
--     Module      : Fixen.IR.AST
--     Description : Data structures for programs freshly baked by the parser.
--     Copyright   : (c) Programming Languages Innovation Lab@NUS
--     License     : MIT
--     Maintainer  : yongqi@nus.edu.sg
--     Stability   : experimental
--
--     This module defines the core data structures that are generated by
--     the parser; these are, essentially, abstract syntax trees. The nodes in
--     the AST are annotated with source positions.
module Fixen.IR.AST where

import Data.List.NonEmpty
import Data.Map.Strict
import Data.Text (Text)
import Error.Diagnose.Position (Position)
import Fixen.Data.AlaCarte
import Fixen.IR.Core qualified as Core
import Fixen.IR.Core.Annotations
import GHC.Natural (Natural)

type SimpleIdentifier = Core.SimpleIdentifier Position Text

type ModuleName = Core.ModuleName Position (NonEmpty SimpleIdentifier)

type FullyQualifiedName = Core.FullyQualifiedName Position ModuleName SimpleIdentifier

type Identifier = Core.Identifier Position ModuleName SimpleIdentifier Text

type Expr = Core.Expr Position Identifier Integer Text

type Type = Core.Type Position Identifier Natural Text

type Relation =
  Core.Relation
    Position
    SimpleIdentifier
    [Type]

type Assumption = Core.Fact Position SimpleIdentifier [SimpleIdentifier]

type Condition = Core.Condition Position Expr

type Conclusion = Core.Fact Position SimpleIdentifier [Expr]

type Rule =
  Core.Rule
    Position
    (Maybe SimpleIdentifier)
    (Maybe [SimpleIdentifier])
    [Assumption]
    [Condition]
    Conclusion

type Extern = Core.Extern Position (NonEmpty SimpleIdentifier)

type HsImport = Core.HsImport Position Text
type Include = Core.Include Position Text

type HsBlock = Core.HsBlock Position (Maybe SimpleIdentifier) Text

type RuleInstantiation = Core.RuleInstantiation Position SimpleIdentifier (Map SimpleIdentifier SimpleIdentifier)

type PriorityOrd = Core.PriorityOrd Position Expr RuleInstantiation

type Priority = Core.Priority Position [PriorityOrd]

type Query = Core.Query Position SimpleIdentifier Identifier [Core.Mode]

type ModuleDeclaration = Core.ModuleDeclaration Position ModuleName

type PartialOrdDeclaration = Core.PartialOrdDeclaration Position SimpleIdentifier Type Expr Expr

-- | We probably want something data type to denote "everything else". Then later,
-- once everything has been parsed, we can actually collect all the rules that
-- belong to this "everything else" phase.
newtype EverythingElseRuleset = EverythingElseRuleset Position
  deriving (Show, Eq)

type Phases = Core.Phases Position (Core.Ruleset Position [SimpleIdentifier] :+: EverythingElseRuleset)

data Program = Program
  { hsBlocks :: [HsBlock]
  , priorities :: Maybe Priority
  , queries :: [Query]
  , moduleName :: ModuleDeclaration
  , hsImports :: [HsImport]
  , extern :: Maybe Extern
  , relations :: [Relation]
  , rules :: [Rule]
  , includes :: [Include]
  , phases :: Maybe Phases
  , partialOrdDeclarations :: [PartialOrdDeclaration]
  }
  deriving (Show, Eq)

-- * Annotations

-- | Gets the source position of something in the AST.
getPosition
  :: forall group e
   . (group :>: Position, GetAnnotation group e)
  => e
  -> Position
getPosition = getAnnotationOf @Position

-- | Sets the source position of something in the AST.
setPosition
  :: forall group e e'
   . (group :>: Position, SetAnnotation group e e', GetAnnotation group e)
  => Position
  -> e
  -> e'
setPosition = setAnnotationOf @Position
