-- |
--     Module      : Fixen.IR.AST
--     Description : Data structures for programs freshly baked by the parser.
--     Copyright   : (c) Programming Languages Innovation Lab@NUS
--     License     : MIT
--     Maintainer  : yongqi@nus.edu.sg
--     Stability   : experimental
--
--     This module defines the core data structures that are generated by
--     the parser; these are, essentially, abstract syntax trees. The nodes in
--     the AST are annotated with source positions.
module Fixen.IR.AST where

import Data.List.NonEmpty
import Data.Map.Strict
import Data.Text (Text)
import Error.Diagnose.Position (Position)
import Fixen.Data.AlaCarte
import Fixen.IR.Core qualified as Core
import Fixen.IR.Core.Annotations
import GHC.Natural (Natural)

type SimpleIdentifier = Core.SimpleIdentifier Position Text

type ModuleName = Core.ModuleName Position (NonEmpty SimpleIdentifier)

type FullyQualifiedName = Core.FullyQualifiedName Position ModuleName SimpleIdentifier

type Identifier = Core.Identifier Position ModuleName SimpleIdentifier Text

type Expr = Core.Expr Position Identifier Integer Text

type Type = Core.Type Position Identifier Natural Text

type RelationArgument = Core.RelationArgument Position Core.SubsumptionAnnotation Type

type Relation =
  Core.Relation
    Position
    SimpleIdentifier
    [RelationArgument]

type Assumption = Core.Fact Position SimpleIdentifier [SimpleIdentifier]

type Condition = Core.Condition Position Expr

type Conclusion = Core.Fact Position SimpleIdentifier [Expr]

type Rule =
  Core.Rule
    Position
    (Maybe SimpleIdentifier)
    (Maybe [SimpleIdentifier])
    [Assumption]
    [Condition]
    Conclusion

type Extern = Core.Extern Position (NonEmpty SimpleIdentifier)

-- May actually be unused
type Completion = Core.Completion Position Identifier SimpleIdentifier

type HsImport = Core.HsImport Position Text
type Use = Core.Use Position Text (Core.InclusionOrExclusion Position [SimpleIdentifier] [SimpleIdentifier])

type HsBlock = Core.HsBlock Position (Maybe SimpleIdentifier) Text

type RuleInstantiation = Core.RuleInstantiation Position SimpleIdentifier (Map SimpleIdentifier SimpleIdentifier)

type PriorityOrd = Core.PriorityOrd Position Expr RuleInstantiation

type Priority = Core.Priority Position [PriorityOrd]

type Query = Core.Query Position SimpleIdentifier Identifier [Core.Mode]

type GenerateIncludeOrExclude = Core.InclusionOrExclusion Position (NonEmpty SimpleIdentifier) (NonEmpty SimpleIdentifier)

-- The reason we use `Maybe GenerateIncludeOrExclude` is because the original
-- might not have the clause and we don't have source positions for it.
type Generate = Core.Generate Position ModuleName (Maybe GenerateIncludeOrExclude)

data Program = Program
  { hsBlocks :: [HsBlock]
  , priorities :: Maybe Priority
  , queries :: [Query]
  , generate :: Maybe Generate
  , hsImports :: [HsImport]
  , extern :: Maybe Extern
  , relations :: [Relation]
  , rules :: [Rule]
  }
  deriving (Show, Eq)

-- * Annotations

-- | Gets the source position of something in the AST.
getPosition
  :: forall group e
   . (group :>: Position, GetAnnotation group e)
  => e
  -> Position
getPosition = getAnnotationOf @Position

-- | Sets the source position of something in the AST.
setPosition
  :: forall group e e'
   . (group :>: Position, SetAnnotation group e e', GetAnnotation group e)
  => Position
  -> e
  -> e'
setPosition = setAnnotationOf @Position
